### GitHub GraphQL: First 10 Issues for User (HTTP)

@githubToken = {{$dotenv GITHUB_TOKEN}}

@userName = diberry
@searchQuery = involves:{{userName}}

POST https://api.github.com/graphql
Authorization: Bearer {{githubToken}}
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

query ($searchQuery: String!) {
  search(query: $searchQuery, type: ISSUE, first: 10) {
    issueCount
    edges {
      node {
        ... on Issue {
          __typename
          id
          number
          title
          url
          createdAt
          state
        }
        ... on PullRequest {
          __typename
          id
          number
          title
          url
          createdAt
          state
          merged
        }
      }
    }
  }
}

{
  "searchQuery": "{{searchQuery}}"
}

