### GitHub GraphQL: First 10 Issues for User (HTTP)

@githubToken = {{$dotenv GITHUB_TOKEN}}

@userName = dfberry
@daysAgo = 7
@sinceDate = {{$datetime 'YYYY-MM-DD' -{{daysAgo}} d}}
@searchQuery = involves:{{userName}} (created:>={{sinceDate}} OR updated:>={{sinceDate}} OR merged:>={{sinceDate}} OR closed:>={{sinceDate}})

POST https://api.github.com/graphql
Authorization: Bearer {{githubToken}}
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

query {
  search(query: "involves:dfberry", type: ISSUE, first: 100) {
    issueCount
    nodes {
      __typename
      ... on Issue {
        id
        number
        title
        url
        state
        createdAt
        updatedAt
        closedAt
        author { login }
      }
      ... on PullRequest {
        id
        number
        title
        url
        state
        createdAt
        updatedAt
        closedAt
        mergedAt
        merged
        author { login }
      }
    }
  }
}

