name: Repository Health Check

on:
  schedule:
    # Run every night at midnight
    - cron: '0 0 * * *'
  workflow_dispatch:  # Allow manual trigger

jobs:
  health-check:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install @actions/core @actions/github axios

      - name: Run health check
        run: |
          cd packages/health-check
          node dist/index.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RUN_HEALTH_CHECK=1
          RUN_GENERATE_README=1
          RUN_SUGGEST_REPOS=1
          RUN_CONTRIBUTOR_ACTIVITY=1

      - name: Upload all generated files
        uses: actions/upload-artifact@v3
        with:
          name: generated-files
          path: generated/

      - name: Add job summary
        run: cat health-check-report.md >> $GITHUB_STEP_SUMMARY

      - name: Commit report to repository
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add health-check-report.md
          git commit -m "Update report" || echo "No changes to commit"
          git push
        env:
          # Need a token with write permissions
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
  create-pr:
    needs: health-check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout azure-javascript repo
        uses: actions/checkout@v4
        with:
          repository: diberry/azure-javascript
          token: ${{ secrets.PR_TOKEN }}
          
      - name: Download generated files
        uses: actions/download-artifact@v3
        with:
          name: generated-files
          path: downloaded-files
          
      - name: Create branch and PR
        run: |
          # Create a new branch with today's date
          BRANCH_NAME="update-generated-files-$(date +'%Y-%m-%d')"
          git checkout -b $BRANCH_NAME
          
          # Copy files from downloaded-files to appropriate locations
          cp -r downloaded-files/* .
          
          # Commit changes
          git add .
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git commit -m "Update generated files $(date +'%Y-%m-%d')" || echo "No changes to commit"
          
          # Push to branch
          git push -u origin $BRANCH_NAME
          
          # Create PR using GitHub CLI
          gh pr create --title "Update generated files $(date +'%Y-%m-%d')" \
                      --body "Automated PR with updated generated files" \
                      --repo azure-samples/azure-javascript \
                      --base main
        env:
          GITHUB_TOKEN: ${{ secrets.PR_TOKEN }}